<?php

/**
 * Implements hook_block_info().
 */
function my_module_block_info() {
	$blocks['my_module'] = array(
		'info' => t('my_module'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
		);
	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function my_module_block_view($delta = '') {
	$block = array();
	switch ($delta) {
		case 'my_module':{
		$block['subject'] = t('');
		$block['content'] = my_module_block_contents($delta);
			break;
		}
	}
	return $block;
}

/**
 * Implements hook_block_contents().
 */
function my_module_block_contents($delta) {
	

	$html = '';
	$html .= '
		<h1>This is my profile.</h1>
		<p>My name is Hongyu. I am 21 years old.</p>
		<p>My favorite food is Dimsum.</p>
		<p> <img border="0" src="http://upload.wikimedia.org/wikipedia/commons/e/ef/Dimsum-shanghai.JPG" alt="Dimsum" width="304" height="228"></p>
	';
	$dayofweek = rand(0,6);
    $html .= "<p>";
	if ($dayofweek == 0 ){
            $html .= "Today is Monday, and I am happy";
    }
    else if ($dayofweek == 1) {
            $html .= "Today is Tuesday, and I am happy";
    }
    else if ($dayofweek == 2) {
             $html .= "Today is Wednesday, and I am happy";
    }
    else if ($dayofweek == 3) {
             $html .= "Today is Thursday, and I am happy";
    }
    else if ($dayofweek == 4) {
             $html .= "Today is Friday, and I am happy";
    }
    else if ($dayofweek == 5) {
             $html .= "Today is Saturday, and I am happy";
    }
    else if ($dayofweek == 6) {
             $html .= "Today is Sunday, and I am happy";
    }
    $html .="</p>";
    
    $html .="<p>End of the page.</p>";
    
    return $html;


}

?>
